# Generated by Django 5.1.6 on 2025-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
    ]
