# Generated by Django 5.1.6 on 2025-03-10 06:41

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.course'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
