# Generated by Django 5.1.6 on 2025-03-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_quiz_course_alter_course_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
    ]
