# Generated by Django 5.1.6 on 2025-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
