# Generated by Django 5.1.6 on 2025-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('instructor', 'instructor'), ('student', 'student')], default='student', max_length=20),
        ),
    ]
